Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'
urlpatterns = [
    path('', views.posts, name='posts'),
    path('new_post/', views.new_post, name='new_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete/<int:post_id>',views.delete_post,name='delete'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #Default authorisation
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('register/', views.register, name='register'),
    
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    '''A blog'''
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''Return a string representation of the model.'''
        return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost

class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Заголовок поста', 'text': 'Текст поста'}
        widgets = {'title': forms.TextInput(),
                   'text': forms.Textarea(attrs={'cols':80})}

blogs/views.py
from django.shortcuts import render, redirect
from .models import BlogPost
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


@login_required
def posts(request):
    posts = BlogPost.objects.filter(owner=request.user).order_by('-date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)


@login_required
def new_post(request):
    #post = BlogPost.objects.get(id=post_id)
    if request.method != 'POST':
# Данные не отправлялись; создается пустая форма.
        form = PostForm()
    else:
# Отправлены данные POST; обработать данные.
        form = PostForm(data=request.POST)
        if form.is_valid():
            #new_post = form.save(commit=False)
            #new_post.post = post
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            #form.save()
            return redirect('blogs:posts')

# Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)



@login_required
def edit_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    if request.method != 'POST':
# Данные не отправлялись; создается пустая форма.
        form = PostForm(instance=post)
    else:
# Отправлены данные POST; обработать данные.
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            #new_post = form.save(commit=False)
            #new_post.post = post
            form.save()
            return redirect('blogs:posts')

# Вывести пустую или недействительную форму.
    context = {'post':post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

@login_required
def delete_post(request,post_id=None):
    post_to_delete=BlogPost.objects.get(id=post_id)
    post_to_delete.delete()
    return redirect('blogs:posts')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:posts')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/backup/base.html
<p>
  <a href="{% url 'blogs:posts' %}">Домашняя страница блога</a> - 
  {% if user.is_authenticated %}
    Привет, {{ user.username }}!
    <a href="{% url 'users:logout' %}">Выйти</a> 
  {% else %}
    Вы не вошли.
    <a href="{% url 'users:register' %}">Зарегистрироваться</a> - 
    <a href="{% url 'users:login' %}">Войти</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

blogs/templates/blogs/backup/edit_post.html
{% extends "blogs/base.html" %}
{% block content %}

  <p>Редактировать пост:</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Сохранить изменения</button>
  </form>

{% endblock content %}

blogs/templates/blogs/backup/new_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p>Добавить новый пост:</p>
  <form action="{% url 'blogs:new_post' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Добавить пост</button>
  </form>

{% endblock content %}

blogs/templates/blogs/backup/posts.html
{% extends "blogs/base.html" %}

{% block content %}

 <p>Посты блога</p>

 <ul>
   {% for post in posts %}
     <li>
	<h4>{{ post.date_added|date:'M d,Y H:i' }}</h4>
	<h4>{{ post.title }}</h4>
	<p>{{ post.text|linebreaks }}</p>
	<p>
	 <a href="{% url 'blogs:edit_post' post.id %}">Редактировать пост</a> - 
	 <a href="{% url 'blogs:delete' post.id %}">Удалить пост</a>
	</p>
     </li>
   {% empty %}
     <li>Постов еще нет :(</li>
   {% endfor %}
 </ul>
 <a href="{% url 'blogs:new_post' %}">Добавить новый пост</a>

{% endblock content %}

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
   <title>Мой дневник</title>

 {% bootstrap_css %}
 {% bootstrap_javascript jquery='full' %}

 </head>
 <body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
  <a class="navbar-brand" href="{% url 'blogs:posts'%}">
       Мой дневник</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse"
  data-target="#navbarCollapse" aria-controls="navbarCollapse"
  aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span></button>
 <div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'blogs:posts'%}">
        Посты</a></li>
  </ul>
  <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <span class="navbar-text"}">Привет, {{ user.username }}!</span>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
      </li>
    {% else %}
      <li class="nav-item">
         <a class="nav-link" href="{% url 'users:register' %}">Зарегистрироваться</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">Войти</a></li>
    {% endif %}
 </ul>
</div>
</nav>


 <main role="main" class="container">
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
  </div>
  <div>
    {% block content %}{% endblock content %}
  </div>
 </main>

</body>

</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% block content %}

  <p>Редактировать пост:</p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Сохранить изменения</button>
  </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <p>Добавить новый пост:</p>
  <form action="{% url 'blogs:new_post' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Добавить пост</button>
  </form>

{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}

{% block page_header %}
 <h1>Посты дневника</h1>
{% endblock page_header %}

{% block content %}

 <ul>
   {% for post in posts %}
     <div class="card mb-3">
         <h4 class="card-header">
	       {{ post.date_added|date:'M d,Y H:i' }}
	       {{ post.title }}
         </h4>
	<div class="card-body">
        {{ post.text|linebreaks }}
    </div>
     <p>
	 <small><a href="{% url 'blogs:edit_post' post.id %}">Редактировать пост</a></small>
	 <small><a href="{% url 'blogs:delete' post.id %}">Удалить пост</a></small>
	 </p>
     </li>
     </div>
   {% empty %}
     <li><h3>Постов еще нет :(</h3></li>
   {% endfor %}
 </ul>
 <a href="{% url 'blogs:new_post' %}">Добавить новый пост</a>

{% endblock content %}